spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/api/v1/user/**
        - id: Auth-Service
          uri: lb://Auth-Service
          predicates:
            - Path=/api/v1/auth/**
        - id: Notes-App
          uri: lb://NOTES-APP
          predicates:
            - Path=/api/v1/notes/**
        - id: Connection-Service
          uri: lb://CONNECTION-SERVICE
          predicates:
            - Path=/api/v1/connection/**

server:
  port: 8081

eureka:
  instance:
    prefer-ip-address=true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

logging:
  level:
    com.netflix.discovery: DEBUG
    org.springframework.cloud.netflix.eureka: DEBUG
